# -*- coding: utf-8 -*-


# Paths
DATA_PATH = "./data/"

# Grid
GRID_SIZE_W = 8
GRID_SIZE_H = 8

# Tiles
TILE_SIZE_W = 64
TILE_SIZE_H = 64
TILE_CENTER_OFFSET_X = TILE_SIZE_W / 2
TILE_CENTER_OFFSET_Y = TILE_SIZE_H / 2

# Screen
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Untitle Strategy Game"

# Drunkard's walk
MAP_PERCENT = (GRID_SIZE_W * GRID_SIZE_H) / 100
DIG_PERCENT_MIN = int(MAP_PERCENT * 55)
DIG_PERCENT_MAX = int(MAP_PERCENT * 65)
DIG_PERCENT_QUADRANT_TOLERANCE_NEGATIVE = 40
DIG_PERCENT_QUADRANT_TOLERANCE_POSITIVE = 40

# Map
BUILDINGS_NUMBER_MIN = 5
BUILDINGS_NUMBER_MAX = 7
LONGEST_VALID_PATH = 20

# Beings
PLAYER_BEINGS_NO = 3
ENEMY_BEINGS_INITIAL_NO = 4

# AI
AI_BUILDING_PRIORITY = 8  # AI search _around_ building, and
AI_KILL_PLAYER_PRIORITY = 7  # _under_ player beings, so
AI_ATTACK_PLAYER_PRIORITY = 5  # the values must be set accordingly.
AI_ATTACK_OWN_PRIORITY = 3
AI_WALK_PRIORITY = 1
AI_RANGE_FALLOFF = 1
AI_INFO_ORDER_PRIORITY = 0
AI_INFO_ORDER_OBJECT = 1
AI_INFO_ORDER_PATH = 2

# FPS-related values
FPS_RATE_DEFAULT = 1 / 60
FPS_RATE_ANIMATION = 1 / 10
