# -*- coding: utf-8 -*-


# Paths
DATA_PATH = "./data/"

# Grid
GRID_SIZE_W = 8
GRID_SIZE_H = 8

# Tiles
TILE_SIZE_W = 64
TILE_SIZE_H = 64
TILE_CENTER_OFFSET_X = TILE_SIZE_W / 2
TILE_CENTER_OFFSET_Y = TILE_SIZE_H / 2

# Screen
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Untitle Strategy Game"

# Drunkard's walk
MAP_PERCENT = (GRID_SIZE_W * GRID_SIZE_H) / 100
DIG_PERCENT_MIN = int(MAP_PERCENT * 55)
DIG_PERCENT_MAX = int(MAP_PERCENT * 75)
DIG_PERCENT_QUADRANT_TOLERANCE_NEGATIVE = 40
DIG_PERCENT_QUADRANT_TOLERANCE_POSITIVE = 40
